database:
  engine: sqlite
  name: devicevault.sqlite3

# Application timezone - used for display and scheduling
# All times are stored in UTC in the database
# Valid timezone names: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Australia/Sydney

local_admin:
  username: admin
  encrypted_password: ''
auth:
  type: Local
  local_enabled: true
new_database:
  engine: ''
  name: ''
